[theme]
primaryColor = "#EF3F4A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F5F9"
textColor = "#0A2148"
font = "sans serif"

[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false
